# Generated by Django 4.2.25 on 2025-11-12 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoredSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField(unique=True)),
                ('check_frequency', models.IntegerField(default=5, help_text='Frequency (in minutes) to check site status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitored_sites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'url')},
            },
        ),
        migrations.CreateModel(
            name='SiteCheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('response_time', models.FloatField(help_text='Response time in seconds')),
                ('is_up', models.BooleanField(default=False)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_results', to='status_monitor.monitoredsite')),
            ],
        ),
    ]
