# Generated by Django 4.2.25 on 2025-11-10 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status_monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='category',
            field=models.CharField(choices=[('CRIT', 'Critical'), ('APP', 'Application'), ('WEB', 'Public Website'), ('DB', 'Database'), ('OTHER', 'Other')], default='WEB', max_length=50),
        ),
    ]
