# Generated by Django 4.2.25 on 2025-11-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status_monitor', '0003_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='response_ime',
            new_name='response_time',
        ),
        migrations.AddField(
            model_name='site',
            name='response_times',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='site',
            name='timestamps',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
